### TD 3.1  Manipulation de vecteurs et de matrices

Dans ce TD, vous devrez répondre à un certain nombre de questions/exercices de base dans un premier temps, et de manipulation de vecteurs et ou matrices ensuite



### 1. (Ecrire un programme pour) Afficher la version de numpy et la configuration de numpy

In [2]:
import numpy
print (numpy.version.version)
numpy.show_config()

1.15.1
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/romain/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/romain/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/romain/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/romain/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/romain/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/romain/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/romain/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/romain/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/romain/anaconda3/lib']

### 2. Afficher, de deux manières, le help de la fonction *arange* (utilisez help et np.info)

In [4]:
import numpy
help(numpy.arange)
numpy.info(numpy.arange)

Help on built-in function arange in module numpy.core.multiarray:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range <http://docs.python.org/lib/built-in-funcs.html>`_ function,
    but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use ``linspace`` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and

### 3. Créer deux matrices (de type array) de dimension 3x3, tester si chaque les matrices  sont égales exactement (élément par élément), ou égales avec une tolérance donnée (par exemple 1e-8).


In [5]:
import numpy as np

a=np.array([[1,1,1],[2,2,2],[3,3,3]])
b=np.array([[1,1,1],[2+1e-7,2-1e-8,2+1e-6],[3,3,3]])

print (a)
print (b)

print(a==b)
print(abs(a-b)<1E-8)

[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[1.         1.         1.        ]
 [2.0000001  1.99999999 2.000001  ]
 [3.         3.         3.        ]]
[[ True  True  True]
 [False False False]
 [ True  True  True]]
[[ True  True  True]
 [False  True False]
 [ True  True  True]]


### 4. Créer une matrice 8x8 et la remplir alternativement avec des 1 et 0 comme un échiquier


In [6]:
import numpy as np

print("Echiquier:")

e=np.zeros((8,8))
e[0::2,1::2]=1
e[1::2,0::2]=1
print (e)

Echiquier:
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


### 5. Générez une matrice aléatoire 4x4 dont les éléments suivent une loi continue uniforme sur l'intervalle [1,3]

In [23]:
import numpy as np
print(2*np.random.random_sample((4, 4))+1)

[[1.8762263  1.73603199 2.00895414 2.32714258]
 [2.77553457 1.89601909 1.65189987 2.701124  ]
 [1.63679165 1.98707508 1.63861893 1.89510353]
 [2.04162254 2.09393121 2.44291462 2.67413616]]


### 6. Ecrivez une commande qui vérifie si un vecteur est bien un vecteur colonne (N lignes N>1, 1 colonne)

In [29]:
import numpy as np

a=np.array([[0.77575789], [0.4534615], [0.35127693]])
b=np.array([[0.39126657,0.4681589],[0.00606601,0.8017327],[0.25688602,0.14995344]])
dim_a=np.shape(a)
print(a)
print((dim_a[1]==1 and dim_a[0]>0) if (len(dim_a)==2) else False)

dim_b=np.shape(b)
print(b)
print((dim_b[1]==1 and dim_b[0]>0) if (len(dim_b)==2) else False)


[[0.77575789]
 [0.4534615 ]
 [0.35127693]]
True
[[0.39126657 0.4681589 ]
 [0.00606601 0.8017327 ]
 [0.25688602 0.14995344]]
False


### 7. Ecrivez une commande qui vérifie si deux matrices ont la même taille

In [25]:
import numpy as np

a=np.array([[0.77575789,0], [0.4534615,0], [0.35127693,0]])
b=np.array([[0.39126657,0.4681589],[0.00606601,0.8017327],[0.25688602,0.14995344]])
dim_a=np.shape(a)
dim_b=np.shape(b)
print(a)
print(b)
print(dim_a==dim_b)

[[0.77575789 0.        ]
 [0.4534615  0.        ]
 [0.35127693 0.        ]]
[[0.39126657 0.4681589 ]
 [0.00606601 0.8017327 ]
 [0.25688602 0.14995344]]
True


### 8. Vérifiez le type de données pour les opérations (a= np.array(b $*$ d)), avec b (d) = 1, 1.01, ..., forcez a à avoir le type int32 et vérifiez la valeur de a.

In [26]:
import numpy as np
a=np.array(1.01*1)
print(a)
print(a.dtype)
a=np.int32(a)
print(a)
print(a.dtype)

1.01
float64
1
int32


### Soit une matrice 3x3 (np.array), extrayez une ligne et une colonne qui soient des np.array de la bonne dimention

In [32]:
import numpy as np
a=np.array([[1,2,3],[0,1,0],[0,0,1]])
print(a[:,[0]])
print(np.shape(a[:,[0]]))
print(a[[0],:])
print(np.shape(a[[0],:]))

[[1]
 [0]
 [0]]
(3, 1)
[[1 2 3]]
(1, 3)


###  Ecrivez une fonction qui effectue un produit scalaire dans $R^n$.  La fonction s'appellera prod_scal($a$,$b$).  Elle testera si $a$ et $b$ ont les bonnes dimensions.

In [129]:

a=np.random.random_sample((4,2))
b=np.random.random_sample((4,2))

print(prod_scal(a,b))
a=np.random.random_sample((4,1))
b=np.random.random_sample((4,2))

print(prod_scal(a,b))

a=np.array([[1.0], [2]])
b=np.array([[4],[5]])
c=prod_scal(a,b)
print(c)
print(prod_scal(a.T,b.T))

vectors should be column vectors
None
vectors should have the same size
None
14.0
vectors should be column vectors
None


In [222]:

a=np.array([[2,4,2],[1,1,0],[0,0,1]])


-2.0


### Ecrivez une fonction qui orthogonalise une base dans $R^n$.  Vous l'appellerez GramS.

In [2]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import numpy as np

def vecteur_colonne(a):
    shape = a.shape;
    if len(shape) <2:
        return False;
    return (shape[0]>1 and shape[1]==1);

def prod_scal(a,b):
    if not (vecteur_colonne(a)) or not (vecteur_colonne(b)) :
        print("Vectors should be column vectors");
        return;
    if a.shape != b.shape :
        print("Vectors should have the same size");
        return;
    return np.sum(a*b)
    
def check_square(a): #Verifie si une matrice a est carrée
    shape = a.shape;
    if len(shape)!=2: # shape doit être de la forme (nb_lignes,nb_colonnes)
        return False;
    return shape[0]==shape[1]; #On verifie si nb_lignes = nb_colonnes

def GramS(a):
    if not check_square(a):
        print("Input matrix should be square");
        return;
        
    nbColumns = a.shape[1]; #Nombre de colonnes, qui correspond au nombre de vecteurs dans la base
    if np.linalg.matrix_rank(a) < nbColumns : #Si rang(M) est inferieur au nombre de colonnes de M, alors M n'est pas de rang max
        print("Matrix should not be rank deficient");
        return; 
    a = a.astype(np.float64); #On a besoin d'avoir des float sinon python rale
    res = np.zeros_like(a); #Crée une matrice de la meme forme que 'a', mais remplie de zeros
    
    #Debut de l'algo de Gram-S
    #On va créer autant de vecteurs que de colonnes dans a
    for i in range(0,nbColumns): 
        nextVector = a[:,[i]]; #Pour créer v_i, on commence en prennant le iéme vecteur de a 
        #On parcourt tous les vecteurs qu'on a déjà créés, et on soustrait à v_i les composantes liées à ces vecteurs 
        for j in range(0,i):   
            previousVector = res[:,[j]];
            nextVector -= prod_scal(nextVector,previousVector)*previousVector

        res[:,[i]]=nextVector/(np.linalg.norm(nextVector)) #On normalise v_i et on l'ajoute a botre base
    return res;

a=np.random.random_sample((4,3))
res=GramS(a)
a=np.array([[2,2,2],[1,1,0],[0,0,1]])
print(a)
res=GramS(a)

a=np.array([[2,4,3],[1,1,0],[0,0,1]])
print(a)

out=GramS(a)
print(out)
print(np.dot(out.T,out))
a=np.array([[1,4,3],[0,1,0],[0,0,1]])
print(a)

out=GramS(a)
print(out)
print(np.dot(out.T,out))
a=np.array([[1,4,3],[0,1,0],[1,0,1]])
print(a)

out=GramS(a)
print(out)
print(np.dot(out.T,out))


Input matrix should be square
[[2 2 2]
 [1 1 0]
 [0 0 1]]
Matrix should not be rank deficient
[[2 4 3]
 [1 1 0]
 [0 0 1]]
[[ 8.94427191e-01  4.47213595e-01 -5.55111512e-16]
 [ 4.47213595e-01 -8.94427191e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 1.00000000e+00  4.25633818e-16 -4.96506831e-16]
 [ 4.25633818e-16  1.00000000e+00 -2.48253415e-16]
 [-4.96506831e-16 -2.48253415e-16  1.00000000e+00]]
[[1 4 3]
 [0 1 0]
 [0 0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 4 3]
 [0 1 0]
 [1 0 1]]
[[ 0.70710678  0.66666667  0.23570226]
 [ 0.          0.33333333 -0.94280904]
 [ 0.70710678 -0.66666667 -0.23570226]]
[[ 1.00000000e+00  2.52702567e-16  6.59639667e-16]
 [ 2.52702567e-16  1.00000000e+00 -5.06735729e-16]
 [ 6.59639667e-16 -5.06735729e-16  1.00000000e+00]]
