### Projet 4: decomposer une image sur une base d'ondlelettes.
========
========
--------
Combal Quentin

Cocogne Romain

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import cv2
import math
import scipy
%matplotlib inline 


 1) Programmer l'algorithme obtenu à la fin de la séance pour un vecteur de taille ${2^{q}}$ où q
est un entier strictement positif arbitraire.

In [31]:
def indicesdemi(depth):
    w=np.zeros((depth,depth))
    for i in range(depth//2):
        w[i,2*i:2*i+2]=0.5
        w[depth//2+i,2*i]=-0.5
        w[depth//2+i,2*i+1]=0.5
    return w

def wn(n,depth):
    w=indicesdemi(depth)
    w_n=np.identity(n)
    w_n[:depth,:depth]=w
    return w_n
def kn(n,depth):
    k=indicesdemi(depth)
    k=2*k.T
    k_n=np.identity(n)
    k_n[:depth,:depth]=k
    return k_n

def decompose1D (vect,q):
    p=vect.size
    w=[]
    while(vect.size>p-2**q+1 and vect.size>1):
        w.append(np.array((vect[1::2]-vect[:-1:2])/2))
        vect=(vect[1::2]+vect[:-1:2])/2
    return vect,w

def decompose1Dmat(vect,q):
    p=vect.size
    i=0
    while(2**i<p and i<q):
        vect=vect@wn(vect.size,vect.size//2**i).T
        i+=1
    return vect

In [32]:
v0=np.array([7,1,6,6,3,-5,4,2])
print(decompose1D(v0,5))
v0=np.array([7,1,6,6,3,-5,4,2])
v0_comp=decompose1Dmat(v0,3)
print(v0_comp)

(array([3.]), [array([-3.,  0., -4., -1.]), array([1., 2.]), array([-2.])])
[ 3. -2.  1.  2. -3.  0. -4. -1.]


In [42]:
def recompose1Dmat(vect):
    p=vect.size
    i=int(np.log2(p))
    while(i>0):
        k=(kn(vect.size,vect.size//2**(i-1)))
        vect=vect@k.T
        i-=1
    return vect

In [43]:
new_v0=recompose1Dmat(v0_comp)
print(new_v0)

[ 7.  1.  6.  6.  3. -5.  4.  2.]


2) Étendre l'algorithme précédent au cas d'une image (Lena.png). Il faudra veiller au formalisme
mathématique lorsque la décomposition sera écrite sous forme matricielle. Programmer
l'algorithme proposé puis étudier et expliquer ses performances sur le image fournies par l'ingénieur.

3)Applications de la transformée de Haar.
Method: